Space Travel Pull Request
eamador1/space-traveling-react-redux pull request #54
Opened 2023-10-20 20:33 UTC by eamador1

About this project : 
---

- This is a project about a webapp named space-traveling-react-redux ✅
- It provides the user the following functionalities:
    - [ ] - Book space travels ✅
    - [ ] - Join missions ✅
    - [ ] - Users can see space travels and join missions booked in my Profile section ✅
For it :
- set-up a GitHub repository ✅
- create a kanbanboard to follow the structure of our project ✅
- set-up react and installed React Redux, Redux Logger, Jest and React Router ✅
- create routes and view components : rockets, missions, dragons, and my profile ✅
- create directories for all Redux state slice files ✅
- use SpaceX API endpoints ✅
- use Redux Hooks, reactBootstrap, actions and reducers ✅
- built our tests✅
- respect the gitflow, and passed the linters: ESLint and Stylelint ✅

2023-10-20 21:38 UTC, Whoistolu reviewed
Hi Team,
@eamador1 , @IvonneBenitesRodriguez and @gilberthappi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Please note that your current git-flow asking to merge your PR from the `development` branch to the `main` branch is correct. However, your group capstone needs its file changes to be in this PR in order for the reviewer to be able to conduct a proper review by passing in in-line comments where necessary, and you need to indicate equal contribution/effort from all the developers as stated by the project requirement.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-10-21 02:12 UTC, Strangeal requested changes
Hi @eamador1, @gilberthappi and @IvonneBenitesRodriguez, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGYyYWNkMjRkY2JjYjg1MjY1M2NjYTNkNWNiNTQwN2EyZGZmNWM5YSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/m3864rBwwBTKMAbpn3/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Professional `README` template ✅ 
- Correct `GitHub` workflow ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 
- Followed *best-practices* ✅ 
- Well structured project ✅ 

## Required Changes ♻️
- [ ] Great job so far in your implementation. However, there's a little issue in your `app.js` and `navigation.js` that I need you to make some adjustments to. Currently, when a user opens your app the first thing they see is a beautiful navigation bar but with no content on the home page and this is because you haven't made the rocket page a default page for your `/` route. 
  - To help make the rocket page your default home page consider going into your `app.js` and changing the path for your `rocket` component to be `/` instead of `/space-traveler` and also consider doing the same in your `navigation.js` by changing the path for your `rocket` to be `/` instead of `/space-traveler`.
  
- [ ] Great job so far building such a beautiful UI for your rockets page. However, there are some adjustments I would like you to make to the styles of your component to make sure it aligns with that of the design provided in the project requirements. Looking at the screenshot provided below you will notice that the `color` of your `button` when a rocket is reserved is not the same as shown on the main design so kindly make sure to make these adjustments as it would help prove your attention to design details.

<table>
<tr>
<th align=“middle”>Main design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="1181" alt="space-travelers__rockets" src="https://github.com/eamador1/space-traveling-react-redux/assets/107192076/3eb7b0b8-43f5-4a59-8901-9c6e74e034f7">
</td>
<td>
<img width="1440" alt="Screenshot 2023-10-21 at 01 47 38" src="https://github.com/eamador1/space-traveling-react-redux/assets/107192076/a0955866-fbcb-4860-85e7-6aadf17b416c">
</td>
</tr>
</table>
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-21 02:12 UTC, Strangeal commented on src/components/MissionList.jsx
- [ ] Great job so far building such a beautiful UI for your missions page. However, there are some adjustments I would like you to make to the styles of your component to make sure it aligns with that of the design provided in the project requirements. Looking at the screenshot provided below you will notice that the `color` of your `button` when you join a mission is not the same as shown on the main design so kindly make sure to make these adjustments as it would help prove your attention to design details.

<table>
<tr>
<th align=“middle”>Main design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="1165" alt="space-travelers__missions" src="https://github.com/eamador1/space-traveling-react-redux/assets/107192076/59a12350-5fe7-49e8-8eee-4a3488136062">

</td>
<td><img width="1440" alt="Screenshot 2023-10-21 at 01 48 26" src="https://github.com/eamador1/space-traveling-react-redux/assets/107192076/fbe0810b-f2bd-44e8-9aa6-8e6f98480761">
</td>
</tr>
</table>

2023-10-21 07:40 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @eamador1, @IvonneBenitesRodriguez & @gilberthappi  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] Application functions as expected :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Pull request has a descriptive title and summary :white_check_mark:  
- [x] Repository has a professional readme file :white_check_mark: 
- [x] Implemented all the changes from the previous reviewer :white_check_mark:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-21 07:40 UTC, gilberthappi commented
Thanks

2024-03-07 12:08 UTC, merged